using System;
using System.Collections.Generic;
using System.Reflection;

namespace AVStore.Core
{
    public abstract class Enumeration : IComparable
    {
        public string Name { get; set; }
        public int Id { get; set;  }
        public Type ValueType { get; set; }

        protected Enumeration()
        {
        }

        protected Enumeration(int id, string name, Type valueType)
        {
            Id = id;
            Name = name;
            ValueType = valueType;
        }

        public override string ToString()
        {
            return Name;
        }

        public static IEnumerable<T> GetAll<T>() where T : Enumeration, new()
        {
            var type = typeof(T);
            var fields = type.GetTypeInfo().GetFields(BindingFlags.Public |
                                                      BindingFlags.Static |
                                                      BindingFlags.DeclaredOnly);
            foreach (var info in fields)
            {
                var instance = new T();
                if (info.GetValue(instance) is T locatedValue)
                {
                    yield return locatedValue;
                }
            }
        }

        public override bool Equals(object obj)
        {
            if (!(obj is Enumeration otherValue))
            {
                return false;
            }
            var typeMatches = GetType() == obj.GetType();
            var valueMatches = Id.Equals(otherValue.Id);
            return typeMatches && valueMatches;
        }

        public int CompareTo(object other)
        {
            return Id.CompareTo(((Enumeration)other).Id);
        }

        // Generated by Resharper
        public override int GetHashCode()
        {
            var hashCode = 2097274640;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Name);
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<Type>.Default.GetHashCode(ValueType);
            return hashCode;
        }

        // Other utility methods ...
    }
}
